name: Docker Compose Actions Workflow
on: push
jobs:
  GCC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with gcc 8
        run: docker-compose run --rm build_gcc_8
      - name: Build with gcc 9
        run: docker-compose run --rm build_gcc_9
      - name: Build with gcc 10
        run: docker-compose run --rm build_gcc_10
      - name: Build with gcc 11
        run: docker-compose run --rm build_gcc_11
      - name: Build with gcc 12
        run: docker-compose run --rm build_gcc_12
      - name: Build with gcc 13
        run: docker-compose run --rm build_gcc_13
  CLANG:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with clang 10
        run: docker-compose run --rm build_clang_10
      - name: Build with clang 11
        run: docker-compose run --rm build_clang_11
      - name: Build with clang 12
        run: docker-compose run --rm build_clang_12
      - name: Build with clang 13
        run: docker-compose run --rm build_clang_13
      - name: Build with clang 14
        run: docker-compose run --rm build_clang_14
      - name: Build with clang 15
        run: docker-compose run --rm build_clang_15
      - name: Build with clang 16
        run: docker-compose run --rm build_clang_16
      - name: Build with clang 17
        run: docker-compose run --rm build_clang_17
